create table if not exists public.ariel_scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 16),
  adjusted_seconds integer not null check (adjusted_seconds between 1 and 86400),
  raw_seconds integer not null check (raw_seconds between 0 and 86400),
  email_failures integer not null default 0 check (email_failures between 0 and 100),
  retries integer not null default 0 check (retries between 0 and 100),
  name_color text not null default '#f3e6c0',
  created_at timestamptz not null default now()
);

alter table public.ariel_scores
  add column if not exists name_color text not null default '#f3e6c0';

create index if not exists ariel_scores_rank_idx
  on public.ariel_scores (adjusted_seconds asc, created_at asc);

alter table public.ariel_scores enable row level security;

drop policy if exists "Scores are publicly readable" on public.ariel_scores;
create policy "Scores are publicly readable"
  on public.ariel_scores
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Anyone can submit a bounded score" on public.ariel_scores;
create policy "Anyone can submit a bounded score"
  on public.ariel_scores
  for insert
  to anon, authenticated
  with check (
    char_length(name) between 1 and 16
    and adjusted_seconds between 1 and 86400
    and raw_seconds between 0 and 86400
    and email_failures between 0 and 100
    and retries between 0 and 100
  );
